### ISSUE TITLE
Python3 code to access the VSX catalog

### ISSUE THREAD

**Issue by KenMighell** [orionlee/PH_TESS_I_LightCurveViewer#1]
These Python3 functions show how to access the VSX catalog using Vizier:

https://github.com/KenMighell/mkpy3/blob/master/mkpy3/mkpy3_vizier_vsx_cone_get_v2.py
https://github.com/KenMighell/mkpy3/blob/master/mkpy3/mkpy3_vizier_catalog_cone_get_v4.py

Kenneth Mighell

Kepler/K2 Support Scientist
SETI Institute
kmighell@seti.org

**Comment by orionlee** [comment]
@KenMighell Thanks for the pointers!
